Repository hawks-atlanta/proxy-python, pull requests merged in 2023-10, with the labels that each got.

#12 chore: Update docker-compose
  docker-compose.yaml
Labels: ci, cd

#14 ci: Linter and formatter
  .github/workflows/integration.yaml
  .github/workflows/testing.yaml
  .gitignore
  .vscode/extensions.json
  README.md
  pages/home/__init__.py
  pages/home/_view.py
  pages/home/_view_test.py
  requirements.txt
  version.py
Labels: ci

#15 feat: endpoint login
  docs/spec.openapi.yaml
  main.py
  pages/home/__init__.py
  pages/home/_view.py
  pages/home/_view_test.py
  requirements.txt
  src/config/environment.py
  src/config/soap_client.py
  src/controllers/_authentication_controllers.py
  src/views/__init__.py
  src/views/_authentication_views.py
  src/views/_authentication_views_test.py
  templates/index.html
Labels: feature

#33 feat: endpoint challenge
  requirements.txt
  src/config/soap_client.py
  src/controllers/_authentication_controllers.py
  src/views/_authentication_views.py
  src/views/_authentication_views_test.py
Labels: feature

#34 release: v0.0.7
  .github/workflows/integration.yaml
  .github/workflows/testing.yaml
  .gitignore
  .vscode/extensions.json
  CHANGELOG.md
  README.md
  docker-compose.yaml
  docs/spec.openapi.yaml
  main.py
  package-lock.json
  package.json
  pages/home/__init__.py
  pages/home/_view.py
  pages/home/_view_test.py
  requirements.txt
  src/config/environment.py
  src/config/soap_client.py
  src/controllers/_authentication_controllers.py
  src/views/__init__.py
  src/views/_authentication_views.py
  src/views/_authentication_views_test.py
  templates/index.html
  version.py
Labels: cd

#37 refactor: Update endpoints
  docs/spec.openapi.yaml
  requirements.txt
  src/controllers/_authentication_controllers.py
  src/lib/faker.py
  src/middlewares/auth_middlewares.py
  src/views/_authentication_views.py
  src/views/_authentication_views_test.py
Labels: documentation, refactor

#38 release: v0.0.8
  CHANGELOG.md
  docs/spec.openapi.yaml
  package-lock.json
  package.json
  requirements.txt
  src/controllers/_authentication_controllers.py
  src/lib/faker.py
  src/middlewares/auth_middlewares.py
  src/views/_authentication_views.py
  src/views/_authentication_views_test.py
Labels: cd

#40 fix: Enable CORS
  CLI.md
  Dockerfile
  main.py
  requirements.txt
  src/config/environment.py
Labels: feature

#39 feat: Register endpoint
  docs/spec.openapi.yaml
  src/controllers/_account_controllers.py
  src/views/__init__.py
  src/views/_account_views.py
  src/views/_account_views_test.py
Labels: feature

#42 Release: v0.0.9
  CHANGELOG.md
  CLI.md
  Dockerfile
  docs/spec.openapi.yaml
  main.py
  package-lock.json
  package.json
  requirements.txt
  src/config/environment.py
  src/controllers/_account_controllers.py
  src/views/__init__.py
  src/views/_account_views.py
  src/views/_account_views_test.py
Labels: cd

#44 fix: Enable all CORS origins
  CLI.md
  Dockerfile
  main.py
  src/config/environment.py
Labels: bug

#45 release: v0.0.11
  CHANGELOG.md
  CLI.md
  Dockerfile
  main.py
  package-lock.json
  package.json
  src/config/environment.py
Labels: ci

#48 ci: Fix tagging pipeline
  .github/workflows/tagging.yaml
  CHANGELOG.md
  package-lock.json
  package.json
  version.json
  version.py
Labels: ci

#41 feat: update docs openapi
  docs/spec.openapi.yaml
Labels: documentation

#49 feat: Endpoint to get the file status
  .github/workflows/tagging.yaml
  docker-compose.yaml
  src/controllers/_account_controllers.py
  src/controllers/_authentication_controllers.py
  src/controllers/_file_controllers.py
  src/views/__init__.py
  src/views/_file_views.py
  src/views/_file_views_test.py
  version.json
Labels: feature

#50 feat: Endpoint to rename a file
  docs/spec.openapi.yaml
  src/controllers/_file_controllers.py
  src/views/_file_views.py
  src/views/_file_views_test.py
Labels: feature

#52 feat: create a folder
  src/controllers/account/__init__.py
  src/controllers/account/register_user/_handler.py
  src/controllers/account/register_user/_register_user_test.py
  src/controllers/account/update_password/_handler.py
  src/controllers/account/update_password/_update_password_test.py
  src/controllers/authentication/__init__.py
  src/controllers/authentication/login/_handler.py
  src/controllers/authentication/login/_login_test.py
  src/controllers/authentication/refresh/_handler.py
  src/controllers/authentication/refresh/_refresh_test.py
  src/controllers/files/__init__.py
  src/controllers/files/check_file_status/_check_file_status_test.py
  src/controllers/files/check_file_status/_handler.py
  src/controllers/files/create_directory/_create_directory_test.py
  src/controllers/files/create_directory/_handler.py
  src/controllers/files/rename_file/_handler.py
  src/controllers/files/rename_file/_rename_file_test.py
  src/views/_account_views.py
  src/views/_authentication_views.py
  src/views/_file_views.py
Labels: feature

#56 fix(files): Keep files extension
  src/controllers/files/rename_file/_rename_file_test.py
  src/controllers/files/upload_file/_handler.py
  src/controllers/files/upload_file/_upload_file_test.py
Labels: bug

#54 test: Increment save file endpoint coverage
  src/controllers/files/upload_file/_handler.py
  src/controllers/files/upload_file/_upload_file_test.py
Labels: ci

#57 release: v0.8.1
  .github/workflows/tagging.yaml
  CHANGELOG.md
  docker-compose.yaml
  docs/spec.openapi.yaml
  package-lock.json
  package.json
  src/controllers/_authentication_controllers.py
  src/controllers/account/__init__.py
  src/controllers/account/register_user/_handler.py
  src/controllers/account/register_user/_register_user_test.py
  src/controllers/account/update_password/_handler.py
  src/controllers/account/update_password/_update_password_test.py
  src/controllers/authentication/__init__.py
  src/controllers/authentication/login/_handler.py
  src/controllers/authentication/login/_login_test.py
  src/controllers/authentication/refresh/_handler.py
  src/controllers/authentication/refresh/_refresh_test.py
  src/controllers/files/__init__.py
  src/controllers/files/check_file_status/_check_file_status_test.py
  src/controllers/files/check_file_status/_handler.py
  src/controllers/files/create_directory/_create_directory_test.py
  src/controllers/files/create_directory/_handler.py
  src/controllers/files/rename_file/_handler.py
  src/controllers/files/rename_file/_rename_file_test.py
  src/controllers/files/upload_file/_handler.py
  src/controllers/files/upload_file/_upload_file_test.py
  src/lib/helpers.py
  src/views/__init__.py
  src/views/_account_views.py
  src/views/_authentication_views.py
  src/views/_file_views.py
  version.json
  version.py
Labels: cd

#58 test(files): Fix broken tests related to file upload
  src/controllers/files/upload_file/_upload_file_test.py
Labels: bug, ci

#59 release: v0.8.1
  src/controllers/files/upload_file/_upload_file_test.py
Labels: cd

#65 fix: Add extra validations for UUIDs
  src/controllers/files/check_file_status/_check_file_status_test.py
  src/controllers/files/check_file_status/_handler.py
  src/controllers/files/create_directory/_create_directory_test.py
  src/controllers/files/create_directory/_handler.py
  src/controllers/files/rename_file/_handler.py
  src/controllers/files/rename_file/_rename_file_test.py
Labels: bug, enhancement

#61 feat: share a file with another user
  src/controllers/files/__init__.py
  src/controllers/files/share_file/_handler.py
  src/controllers/files/share_file/_share_file_test.py
  src/views/_file_views.py
Labels: feature

#64 feat: list user files
  docs/spec.openapi.yaml
  src/controllers/account/register_user/_handler.py
  src/controllers/account/update_password/_handler.py
  src/controllers/authentication/login/_handler.py
  src/controllers/authentication/refresh/_handler.py
  src/controllers/files/__init__.py
  src/controllers/files/check_file_status/_handler.py
  src/controllers/files/create_directory/_handler.py
  src/controllers/files/list_files/_handler.py
  src/controllers/files/list_files/_list_files_test.py
  src/controllers/files/upload_file/_handler.py
  src/views/_file_views.py
Labels: feature

#66 feat: Get file by UUID
  docs/spec.openapi.yaml
  src/controllers/files/__init__.py
  src/controllers/files/get_file_by_uuid/_get_file_by_uuid_test.py
  src/controllers/files/get_file_by_uuid/_handler.py
  src/views/_file_views.py
Labels: feature

#68 feat: move a file
  src/controllers/files/__init__.py
  src/controllers/files/move_a_file/_handler.py
  src/controllers/files/move_a_file/_move_file_test.py
  src/views/_file_views.py
Labels: feature

#69 refactor: Create delete file controller
  src/controllers/files/remove_file/_handler.py
  src/controllers/files/remove_file/_remove_file_test.py
Labels: feature

#73 release: v0.12.0
  CHANGELOG.md
  docs/spec.openapi.yaml
  src/controllers/files/__init__.py
  src/controllers/files/move_a_file/_handler.py
  src/controllers/files/move_a_file/_move_file_test.py
  src/controllers/files/remove_file/_handler.py
  src/controllers/files/remove_file/_remove_file_test.py
  src/controllers/files/shared_file/_handler.py
  src/controllers/files/shared_with_who/_handler.py
  src/controllers/files/unshare_file/_handler.py
  src/controllers/files/unshare_file/_unshare_file_test.py
  src/views/_file_views.py
  version.json
Labels: cd

#77 docs: Add bruno collection
  docs/bruno/README.md
  docs/bruno/account/register.bru
  docs/bruno/account/update-password.bru
  docs/bruno/auth/challenge-and-refresh.bru
  docs/bruno/auth/login.bru
  docs/bruno/bruno.json
  docs/bruno/environments/development.bru
  docs/bruno/files/create-folder-in-folder.bru
  docs/bruno/files/create-folder-in-root.bru
  docs/bruno/files/download-file.bru
  docs/bruno/files/ger-file-status.bru
  docs/bruno/files/get-file-metadata.bru
  docs/bruno/files/list-files-in-folder.bru
  docs/bruno/files/list-files-in-root.bru
  docs/bruno/files/move-file-to-folder.bru
  docs/bruno/files/move-file-to-root.bru
  docs/bruno/files/rename-file.bru
  docs/bruno/files/share-file.bru
  docs/bruno/files/shared-with-who.bru
  docs/bruno/files/upload-file-in-folder.bru
  docs/bruno/files/upload-file-in-root.bru
Labels: documentation

#78 fix: Move files
  src/controllers/files/move_a_file/_handler.py
Labels: bug

#75 feat: Shared with who
  docs/spec.openapi.yaml
  src/controllers/files/__init__.py
  src/controllers/files/shared_with_who/_handler.py
  src/controllers/files/shared_with_who/_shared_with_who_test.py
  src/views/_file_views.py
Labels: feature

#79 release: v0.13.0
  CHANGELOG.md
  docs/bruno/README.md
  docs/bruno/account/register.bru
  docs/bruno/account/update-password.bru
  docs/bruno/auth/challenge-and-refresh.bru
  docs/bruno/auth/login.bru
  docs/bruno/bruno.json
  docs/bruno/environments/development.bru
  docs/bruno/files/create-folder-in-folder.bru
  docs/bruno/files/create-folder-in-root.bru
  docs/bruno/files/download-file.bru
  docs/bruno/files/ger-file-status.bru
  docs/bruno/files/get-file-metadata.bru
  docs/bruno/files/list-files-in-folder.bru
  docs/bruno/files/list-files-in-root.bru
  docs/bruno/files/move-file-to-folder.bru
  docs/bruno/files/move-file-to-root.bru
  docs/bruno/files/rename-file.bru
  docs/bruno/files/share-file.bru
  docs/bruno/files/shared-with-who.bru
  docs/bruno/files/upload-file-in-folder.bru
  docs/bruno/files/upload-file-in-root.bru
  docs/spec.openapi.yaml
  src/controllers/files/__init__.py
  src/controllers/files/move_a_file/_handler.py
  src/controllers/files/shared_with_who/_handler.py
  src/controllers/files/shared_with_who/_shared_with_who_test.py
  src/views/_file_views.py
  version.json
Labels: cd

#80 feat: Endpoint to get the files shared with the user
  docs/bruno/files/get-shared-with-me.bru
  src/controllers/files/__init__.py
  src/controllers/files/shared_file/_handler.py
  src/controllers/files/shared_file/_shared_file_test.py
  src/views/_file_views.py
Labels: feature

#81 release: v0.14.0
  CHANGELOG.md
  docs/bruno/files/get-shared-with-me.bru
  src/controllers/files/__init__.py
  src/controllers/files/shared_file/_handler.py
  src/controllers/files/shared_file/_shared_file_test.py
  src/views/_file_views.py
  version.json
Labels: cd

#82 feat: remove a file
  docs/bruno/files/delete-file.bru
  src/controllers/files/__init__.py
  src/controllers/files/remove_file/_handler.py
  src/controllers/files/remove_file/_remove_file_test.py
  src/views/_file_views.py
Labels: feature

#83 release: v0.15.0
  CHANGELOG.md
  docs/bruno/files/delete-file.bru
  src/controllers/files/__init__.py
  src/controllers/files/remove_file/_handler.py
  src/controllers/files/remove_file/_remove_file_test.py
  src/views/_file_views.py
  version.json
Labels: cd
